game::level::SubmitHandler
static Submit game.level.SubmitHandler.createSubmit(Point point)
Referenced by game.gui.component.PlayerInputLine.submitFunction, game.gui.component.PlayerInputLinearFunction.submitFunction, game.gui.component.PlayerInputPointDepth.submitFunction, game.gui.component.PlayerInputPointDistance.submitFunction.
static Submit game.level.SubmitHandler.createSubmit(LinearFunction linearFunction)