game::controller::LevelController
IntegerProperty game.controller.LevelController.successfulHits
AbstractLevel game.controller.LevelController.level
AbstractLevelRenderer game.controller.LevelController.playerInputRenderer
BackgroundRenderer game.controller.LevelController.backgroundRenderer
AbstractPlayerInput game.controller.LevelController.playerInput
Pane game.controller.LevelController.gameWrapper
final GameController game.controller.LevelController.gameController
game.controller.LevelController.LevelController(GameController gameController)
References game.gui.level.BackgroundRenderer.initializeBackground, game.controller.LevelController.buildLevel, game.controller.LevelState.LEVEL_2.
void game.controller.LevelController.buildLevel(LevelState state)
Builds a fully functional game level which is comprised of a renderer, a player input and level object state the level to use for building the level
Referenced by game.controller.LevelController.LevelController, game.controller.LevelController.onInputSubmit.
Node game.controller.LevelController.getPlayerInput()
the current player input
References game.gui.component.PlayerInput.getSubmitInput.
Pane game.controller.LevelController.getWrapper()
returns the container of the renderer than the renderer by itself The wrapper itself is responsible for the dynamic resizing functionality
Referenced by game.controller.GameController.GameController.
AbstractLevelRenderer game.controller.LevelController.getLevelRenderer()
returns the container of the renderer than the renderer by itself The wrapper itself is responsible for the dynamic resizing functionality
Canvas game.controller.LevelController.getBackground()
the BackgroundRenderer
AbstractLevel game.controller.LevelController.getLevel()
the current level object
Referenced by game.controller.GameController.GameController, game.controller.GameController.onLevelCompleted, game.gui.Client.start, game.gui.component.PlayerInputLine.getSubmitInput, game.gui.component.PlayerInputLinearFunction.getSubmitInput, game.gui.component.PlayerInputPoint.getSubmitInput, game.gui.component.PlayerInputPointDepth.submitFunction, game.gui.component.PlayerInputPointDistance.getSubmitInput, game.gui.component.PlayerInputPointDistance.submitFunction.
void game.controller.LevelController.onInputSubmit(SubmitObject submit)
this method is triggered, when a submit is entered to be validated. submit
References game.level.AbstractLevel.validate, game.gui.component.StatusMessage.display, game.gui.component.StatusMessageType.TYPE_CORRECT, game.gui.level.BackgroundRenderer.startAnimation, game.gui.level.AbstractLevelRenderer.redraw, game.gui.component.StatusMessageType.TYPE_WRONG, game.level.Level.getWinCondition, game.controller.LevelController.buildLevel, game.level.Level.getNextLevelState, game.controller.GameController.onLevelCompleted, game.level.Level.getCurrentState, game.gui.level.BackgroundRenderer.stopAnimation.
Referenced by game.gui.component.PlayerInputLine.getSubmitInput, game.gui.component.PlayerInputLinearFunction.getSubmitInput, game.gui.component.PlayerInputPoint.getSubmitInput, game.gui.component.PlayerInputPointDistance.getSubmitInput.
BackgroundRenderer game.controller.LevelController.getBackgroundLayer()
the background and animation canvas
void game.controller.LevelController.setLevelByLevelState(LevelState state)
Instantiates a new Level object. state the level to use for building the level
void game.controller.LevelController.setRendererByLevelState(LevelState state)
Instantiates a new AbstractLevelRenderer object by level and binds the BackgroundRenderer to the game´s wrapper. The bindings are necessary to set the canvas´ size according to the client´s current window size. state the level to use for building the renderer
void game.controller.LevelController.setPlayerInputByLevelState(LevelState state)
initializes the required input for solving the level state the level to use for building the player input
void game.controller.LevelController.setAnimationRendererByLevelState(LevelState state)
sets the Animation which is played after a correct player input state the level to use for building the level
void game.controller.LevelController.resetGameController()
When a level is finished, the wrapper and input need to reset to the layout