game::gui::component::GameRenderer
DoubleProperty game.gui.component.GameRenderer.scoreRenderer
IntegerProperty game.gui.component.GameRenderer.levelProgressRenderer
IntegerProperty game.gui.component.GameRenderer.currentLevelRenderer
Node game.gui.component.GameRenderer.levelDescription
game.gui.component.GameRenderer.GameRenderer()
References game.gui.component.GameRenderer.redraw.
void game.gui.component.GameRenderer.setLevelProgressRenderer(int level)
level
void game.gui.component.GameRenderer.setCurrentLevelRenderer(int currentLevel)
currentLevel
IntegerProperty game.gui.component.GameRenderer.getLevelProgressRenderer()
Referenced by game.controller.GameController.changed.
DoubleProperty game.gui.component.GameRenderer.getScoreRenderer()
Referenced by game.controller.GameController.GameController.
IntegerProperty game.gui.component.GameRenderer.getCurrentLevelRenderer()
Referenced by game.controller.GameController.GameController.
void game.gui.component.GameRenderer.redraw()
(re)draws the GameRenderer onto the client
References game.gui.component.LevelIntroBox.display.
Referenced by game.controller.GameController.changed, game.controller.GameController.setCurrentLevel, game.gui.component.GameRenderer.GameRenderer.
void game.gui.component.GameRenderer.setLevelDescription(Node levelDescription)
levelDescription
Referenced by game.controller.GameController.GameController, game.controller.GameController.onLevelCompleted.