game::module::math::Rational
Rational game.module.math.Rational.zero
int game.module.math.Rational.num
int game.module.math.Rational.den
game.module.math.Rational.Rational(int num, int den)
num den
References game.module.math.Rational.calculateGreatestCommonDivisor.
Referenced by game.module.math.Rational.multiply, game.module.math.Rational.reciprocal, game.module.math.Rational.equals.
double game.module.math.Rational.toDouble()
return double precision representation of the rational number
Referenced by game.module.geometry.shape.LinearFunction.getIntercept, game.module.geometry.shape.LinearFunction.getRawIntercept, game.module.geometry.shape.LinearFunction.getInterceptByPointA, game.module.geometry.shape.LinearFunction.calculateY, game.module.geometry.shape.LinearFunction.calculateX.
int game.module.math.Rational.compareTo(Rational b)
Referenced by game.module.math.Rational.equals.
Rational game.module.math.Rational.multiply(int factor)
References game.module.math.Rational.Rational.
Referenced by game.module.geometry.shape.LinearFunction.calculateY.
Rational game.module.math.Rational.reciprocal()
References game.module.math.Rational.Rational.
Referenced by game.module.geometry.shape.LinearFunction.calculateX.
boolean game.module.math.Rational.equals(Object b)
Checks if RationalA equals RationalB b Another Rational object bool
References game.module.math.Rational.Rational, game.module.math.Rational.compareTo.
int game.module.math.Rational.getNum()
getter of num
Referenced by game.gui.component.PlayerInputLine.getSubmitInput, game.gui.component.PlayerInputLinearFunction.getSubmitInput, game.gui.component.PlayerInputPoint.getSubmitInput, game.gui.component.PlayerInputPointDistance.getSubmitInput, game.module.geometry.shape.Point.factor.
int game.module.math.Rational.getDen()
getter of den
Referenced by game.gui.component.PlayerInputLine.getSubmitInput, game.gui.component.PlayerInputLinearFunction.getSubmitInput, game.gui.component.PlayerInputPoint.getSubmitInput, game.gui.component.PlayerInputPointDistance.getSubmitInput, game.module.geometry.shape.Point.factor.
String game.module.math.Rational.toString()
static int game.module.math.Rational.calculateGreatestCommonDivisor(int m, int n)
Calculates the greatest common divisor between two integers m n
Referenced by game.module.math.Rational.Rational.