game::gui::level::LevelAnimationRenderer
Canvas game.gui.level.LevelAnimationRenderer.canvas
LinearFunction game.gui.level.LevelAnimationRenderer.currentFunction
game.gui.level.LevelAnimationRenderer.LevelAnimationRenderer(Canvas canvas)
abstract void game.gui.level.LevelAnimationRenderer.startAnimation(Canvas canvas)
Referenced by game.gui.level.BackgroundRenderer.startAnimation.
void game.gui.level.LevelAnimationRenderer.setCurrentFunction(LinearFunction currentFunction)
abstract void game.gui.level.LevelAnimationRenderer.stopAnimation()
Referenced by game.gui.level.BackgroundRenderer.stopAnimation.
LinearFunction game.gui.level.LevelAnimationRenderer.getCurrentFunction()
Referenced by game.gui.level.LevelAnimationRenderer1.startAnimation, game.gui.level.LevelAnimationRenderer2.startAnimation, game.gui.level.LevelAnimationRenderer3.startAnimation, game.gui.level.LevelAnimationRenderer4.startAnimation.
Pane game.gui.level.LevelAnimationRenderer.getAnimationWrapper()
Referenced by game.gui.level.LevelAnimationRenderer1.startAnimation, game.gui.level.LevelAnimationRenderer1.stopAnimation, game.gui.level.LevelAnimationRenderer2.startAnimation, game.gui.level.LevelAnimationRenderer2.stopAnimation, game.gui.level.LevelAnimationRenderer3.startAnimation, game.gui.level.LevelAnimationRenderer3.stopAnimation, game.gui.level.LevelAnimationRenderer4.startAnimation, game.gui.level.LevelAnimationRenderer4.stopAnimation.
Canvas game.gui.level.LevelAnimationRenderer.getCanvas()