game::level::FunctionGeneratorConfig
int game.level.FunctionGeneratorConfig.maxValue
int game.level.FunctionGeneratorConfig.maxIntercept
int game.level.FunctionGeneratorConfig.ax
int game.level.FunctionGeneratorConfig.ay
int game.level.FunctionGeneratorConfig.bx
int game.level.FunctionGeneratorConfig.by
game.level.FunctionGeneratorConfig.FunctionGeneratorConfig()
References game.gui.level.AbstractLevelRenderer.CELL_SIZE.
int game.level.FunctionGeneratorConfig.getMaxValue()
void game.level.FunctionGeneratorConfig.setMaxValue(int max)
Referenced by game.level.Level1.Level1, game.level.Level2.Level2, game.level.Level3.Level3, game.level.Level4.Level4.
void game.level.FunctionGeneratorConfig.setAx(int ax)
void game.level.FunctionGeneratorConfig.setAy(int ay)
void game.level.FunctionGeneratorConfig.setBx(int bx)
void game.level.FunctionGeneratorConfig.setBy(int by)
Referenced by game.level.Level2.Level2.
int game.level.FunctionGeneratorConfig.getAx()
int game.level.FunctionGeneratorConfig.getAy()
int game.level.FunctionGeneratorConfig.getBx()
int game.level.FunctionGeneratorConfig.getBy()
void game.level.FunctionGeneratorConfig.setMaxIntercept(int maxIntercept)
Referenced by game.level.Level1.Level1.
int game.level.FunctionGeneratorConfig.getMaxIntercept()
Referenced by game.level.LinearFunctionGenerator.generateLinearFunction.