game::module::geometry::shape::LinearFunction
game.module.geometry.shape.LinearFunction.LinearFunction(int startX, int startY, int endX, int endY)
Creates a new instance of Line. startX the horizontal coordinate of the start point of the line segment startY the vertical coordinate of the start point of the line segment endX the horizontal coordinate of the end point of the line segment endY the vertical coordinate of the end point of the line segment
game.module.geometry.shape.LinearFunction.LinearFunction(Point x, Point y)
Creates a new instance of Line. startX the horizontal coordinate of the start point of the line segment startY the vertical coordinate of the start point of the line segment endX the horizontal coordinate of the end point of the line segment endY the vertical coordinate of the end point of the line segment
References game.module.geometry.shape.Point.getX, game.module.geometry.shape.Point.getY.
Rational game.module.geometry.shape.LinearFunction.getSlope()
Calculates the slope of the two given points returns the slope as a Rational
Referenced by game.gui.component.PlayerInputLine.getSubmitInput, game.gui.component.PlayerInputLinearFunction.getSubmitInput, game.gui.component.PlayerInputPoint.getSubmitInput, game.gui.component.PlayerInputPointDistance.getSubmitInput, game.module.geometry.shape.LinearFunction.getIntercept, game.module.geometry.shape.LinearFunction.getRawIntercept, game.module.geometry.shape.LinearFunction.getInterceptByPointA, game.module.geometry.shape.LinearFunction.calculateY, game.module.geometry.shape.LinearFunction.calculateX.
int game.module.geometry.shape.LinearFunction.getIntercept()
Calculates the intercept of the line returns the intercept as an integer
References game.module.geometry.shape.LinearFunction.getSlope, game.module.math.Rational.toDouble.
Referenced by game.gui.component.PlayerInputLine.getSubmitInput, game.gui.component.PlayerInputLinearFunction.getSubmitInput, game.gui.component.PlayerInputPoint.getSubmitInput, game.gui.component.PlayerInputPointDistance.getSubmitInput, game.module.geometry.shape.LinearFunction.calculateY, game.module.geometry.shape.LinearFunction.calculateX.
double game.module.geometry.shape.LinearFunction.getRawIntercept()
Calculates the intercept of the line returns the intercept as an integer
References game.module.geometry.shape.LinearFunction.getSlope, game.module.math.Rational.toDouble.
int game.module.geometry.shape.LinearFunction.getInterceptByPointA()
This computes the intercept of the line. The result is the same as getIntercept() Used for testing purposes intercept of the linear function
References game.module.geometry.shape.LinearFunction.getSlope, game.module.math.Rational.toDouble.
Point game.module.geometry.shape.LinearFunction.getPointStart()
returns starting point of line as a Point object
Referenced by game.gui.component.PlayerInputPointDepth.submitFunction, game.gui.component.PlayerInputPointDistance.submitFunction, game.gui.level.LevelAnimationRenderer1.startAnimation, game.gui.level.LevelAnimationRenderer2.startAnimation, game.gui.level.LevelAnimationRenderer3.startAnimation, game.gui.level.LevelAnimationRenderer4.startAnimation, game.gui.level.LevelRenderer2.draw, game.gui.level.LevelRenderer3.draw.
Point game.module.geometry.shape.LinearFunction.getPointEnd()
returns ending point of line as a Point object
Referenced by game.gui.level.LevelAnimationRenderer1.startAnimation, game.gui.level.LevelAnimationRenderer2.startAnimation, game.gui.level.LevelAnimationRenderer3.startAnimation, game.gui.level.LevelAnimationRenderer4.startAnimation, game.gui.level.LevelRenderer2.draw, game.gui.level.LevelRenderer3.draw.
double game.module.geometry.shape.LinearFunction.calculateY(int x)
calculates the y position by a give x x
References game.module.geometry.shape.LinearFunction.getSlope, game.module.math.Rational.multiply, game.module.math.Rational.toDouble, game.module.geometry.shape.LinearFunction.getIntercept.
double game.module.geometry.shape.LinearFunction.calculateX(int y)
calculates the x position by a given y y
References game.module.geometry.shape.LinearFunction.getSlope, game.module.math.Rational.reciprocal, game.module.math.Rational.toDouble, game.module.geometry.shape.LinearFunction.getIntercept.