game::controller::GameController
IntegerProperty game.controller.GameController.level
DoubleProperty game.controller.GameController.score
final GameRenderer game.controller.GameController.gameRenderer
final LevelController game.controller.GameController.levelController
game.controller.GameController.GameController()
References game.controller.LevelController.getWrapper, game.gui.component.GameRenderer.setLevelDescription, game.controller.LevelController.getLevel, game.level.Level.getDescription, game.gui.component.GameRenderer.getScoreRenderer, game.gui.component.GameRenderer.getCurrentLevelRenderer, game.controller.GameController.setCurrentLevel, game.level.AbstractLevel.getLevelByLevelState, game.level.Level.getCurrentState.
void game.controller.GameController.onLevelCompleted()
this is triggered, when the win condition of the current level is reached. Sends events to the GameRenderer to accommodate for the next level´s changes on the GUI
References game.gui.component.GameRenderer.setLevelDescription, game.controller.LevelController.getLevel, game.level.Level.getDescription, game.level.AbstractLevel.getLevelByLevelState, game.level.Level.getCurrentState, game.controller.GameController.setCurrentLevel.
Referenced by game.controller.LevelController.onInputSubmit.
void game.controller.GameController.showHighscoreChart()
void game.controller.GameController.savePlayerScore()
GameRenderer game.controller.GameController.getGameRenderer()
the GameRenderer
Referenced by game.gui.Client.start.
LevelController game.controller.GameController.getLevelController()
the LevelController
Referenced by game.gui.Client.start.
void game.controller.GameController.changed(ObservableValue<? extends Object > observable, Object oldValue, Object newValue)
References game.gui.component.GameRenderer.getLevelProgressRenderer, game.gui.component.GameRenderer.redraw.
void game.controller.GameController.setCurrentLevel(int currentLevel)
References game.gui.component.GameRenderer.redraw.
Referenced by game.controller.GameController.GameController, game.controller.GameController.onLevelCompleted.
double game.controller.GameController.calculateScore(int oldValue, int newValue)
void game.controller.GameController.addToScore(double score)