game::module::geometry::shape::Point
game.module.geometry.shape.Point.Point(int x, int y)
Constructs and initializes a Point2D with the specified coordinates. x the X coordinate of the newly constructed Point2D y the Y coordinate of the newly constructed Point2D
Referenced by game.module.geometry.shape.Point.offsetLocation, game.module.geometry.shape.Point.offsetX, game.module.geometry.shape.Point.offsetY, game.module.geometry.shape.Point.factor.
void game.module.geometry.shape.Point.setLocation(int x, int y)
Sets the location of this Point2D to the specified float coordinates. x the new X coordinate of thisPoint2D y the new Y coordinate of thisPoint2D
Referenced by game.module.geometry.shape.Point.setLocation.
Point game.module.geometry.shape.Point.offsetLocation(int offsetX, int offsetY)
offsets x of Point2D to the specified float coordinates. offsetX the new X coordinate of thisPoint2D offsetY the new Y coordinate of thisPoint2D
References game.module.geometry.shape.Point.Point, game.module.geometry.shape.Point.offsetX, game.module.geometry.shape.Point.offsetY.
Point game.module.geometry.shape.Point.offsetX(int offsetX)
Sets the location of this Point2D to the specified float coordinates. offsetX the new X coordinate of thisPoint2D
References game.module.geometry.shape.Point.Point.
Referenced by game.module.geometry.shape.Point.offsetLocation.
Point game.module.geometry.shape.Point.offsetY(int offsetY)
Sets the location of this Point2D to the specified float coordinates. offsetY
References game.module.geometry.shape.Point.Point.
Referenced by game.module.geometry.shape.Point.offsetLocation.
void game.module.geometry.shape.Point.setLocation(Point p)
Sets the location of this Point2D to the same coordinates as the specified Point2D object. p the specified Point2D to which to set this Point2D
References game.module.geometry.shape.Point.setLocation.
int game.module.geometry.shape.Point.getX()
x of point
Referenced by game.gui.level.LevelAnimationRenderer1.startAnimation, game.gui.level.LevelAnimationRenderer2.startAnimation, game.gui.level.LevelAnimationRenderer3.startAnimation, game.gui.level.LevelAnimationRenderer4.startAnimation, game.gui.level.LevelRenderer2.draw, game.gui.level.LevelRenderer3.draw, game.gui.util.Draw2DHelper.drawCross, game.gui.util.Draw2DHelper.convertPointToCanvas, game.gui.util.Draw2DHelper.pointToCoordinate, game.gui.util.Draw2DHelper.drawLine, game.gui.util.Draw2DHelper.drawImage, game.gui.util.Draw2DHelper.normalizePoint, game.gui.util.Draw2DHelper.denormalizePoint, game.module.geometry.shape.LinearFunction.LinearFunction.
int game.module.geometry.shape.Point.getY()
y of point
Referenced by game.gui.level.LevelAnimationRenderer1.startAnimation, game.gui.level.LevelAnimationRenderer2.startAnimation, game.gui.level.LevelAnimationRenderer3.startAnimation, game.gui.level.LevelAnimationRenderer4.startAnimation, game.gui.level.LevelRenderer3.draw, game.gui.util.Draw2DHelper.drawCross, game.gui.util.Draw2DHelper.convertPointToCanvas, game.gui.util.Draw2DHelper.pointToCoordinate, game.gui.util.Draw2DHelper.drawLine, game.gui.util.Draw2DHelper.drawImage, game.gui.util.Draw2DHelper.normalizePoint, game.gui.util.Draw2DHelper.denormalizePoint, game.module.geometry.shape.LinearFunction.LinearFunction.
void game.module.geometry.shape.Point.setX(int x)
Referenced by game.gui.component.PlayerInputPointDistance.submitFunction.
void game.module.geometry.shape.Point.setY(int y)
Referenced by game.gui.component.PlayerInputPointDepth.submitFunction, game.gui.level.LevelAnimationRenderer2.startAnimation, game.gui.level.LevelAnimationRenderer3.startAnimation, game.gui.level.LevelAnimationRenderer4.startAnimation.
Point game.module.geometry.shape.Point.factor(int factor)
References game.module.geometry.shape.Point.Point.
Point game.module.geometry.shape.Point.factor(Rational rational)
References game.module.geometry.shape.Point.Point, game.module.math.Rational.getNum, game.module.math.Rational.getDen.