game::level::LinearFunctionGenerator
static LinearFunction game.level.LinearFunctionGenerator.generateLinearFunction(FunctionGeneratorConfig config)
generateLinearFunction generates linear functions randomly. config Configurator for the function
References game.level.FunctionGeneratorConfig.getMaxIntercept.
Referenced by game.level.Level1.Level1, game.level.Level2.Level2, game.level.Level3.Level3, game.level.Level4.Level4.
static boolean game.level.LinearFunctionGenerator.isValidSlope(LinearFunction linearFunction, int settingMaxIntercept)
Checks whether the given two points have a valid slope. If not, return false linearFunction settingMaxIntercept
static boolean game.level.LinearFunctionGenerator.isValidIntercept(int currentIntercept, int configMaxIntercept)
Checks whether the linear function´s intercept is absolutely lower than the max intercept setting provided by the config currentIntercept configMaxIntercept
static int game.level.LinearFunctionGenerator.getRandomNumber(int min, int max)
min max random number
static LinearFunction game.level.LinearFunctionGenerator.generate(FunctionGeneratorConfig config)
point a is always below the x axis and point b alway above the x axis config