game::gui::component::AlertBox
static void game.gui.component.AlertBox.display(String title, String message)
title message Boolean
Referenced by game.gui.component.PlayerInputLine.getSubmitInput, game.gui.component.PlayerInputLinearFunction.getSubmitInput, game.gui.component.PlayerInputPoint.getSubmitInput, game.gui.component.PlayerInputPointDistance.getSubmitInput.