game::level::AbstractLevel
LinearFunction game.level.AbstractLevel.function
LinearFunction game.level.AbstractLevel.getFunction()
Referenced by game.gui.component.PlayerInputLine.getSubmitInput, game.gui.component.PlayerInputLinearFunction.getSubmitInput, game.gui.component.PlayerInputPoint.getSubmitInput, game.gui.component.PlayerInputPointDepth.submitFunction, game.gui.component.PlayerInputPointDistance.getSubmitInput, game.gui.component.PlayerInputPointDistance.submitFunction, game.level.Level1.Level1, game.level.Level2.Level2, game.level.Level3.Level3, game.level.Level4.Level4.
void game.level.AbstractLevel.setFunction(LinearFunction function)
Referenced by game.level.Level1.Level1, game.level.Level2.Level2, game.level.Level3.Level3, game.level.Level4.Level4.
boolean game.level.AbstractLevel.validate(SubmitObject submit)
References game.level.SubmitObject< T >.getSubmit.
Referenced by game.controller.LevelController.onInputSubmit.
Node game.level.AbstractLevel.getBriefing()
boolean game.level.AbstractLevel.validateLine(LinearFunction controlFunction)
boolean game.level.AbstractLevel.validatePoint(Point point)
static int game.level.AbstractLevel.getLevelByLevelState(LevelState levelState)
Referenced by game.controller.GameController.GameController, game.controller.GameController.onLevelCompleted.