game::gui::component::NumberFieldInput
IntegerProperty game.gui.component.NumberFieldInput.maxLength
StringProperty game.gui.component.NumberFieldInput.restrict
game.gui.component.NumberFieldInput.NumberFieldInput()
IntegerProperty game.gui.component.NumberFieldInput.maxLengthProperty()
The max length property.The max length property.
int game.gui.component.NumberFieldInput.getMaxLength()
Gets the max length of the text field.The max length.
void game.gui.component.NumberFieldInput.setMaxLength(int maxLength)
Sets the max length of the text field. maxLength The max length.
StringProperty game.gui.component.NumberFieldInput.restrictProperty()
The restrict property.The restrict property.
String game.gui.component.NumberFieldInput.getRestrict()
Gets a regular expression character class which restricts the user input.The regular expression. getRestrict()
void game.gui.component.NumberFieldInput.setRestrict(String restrict)
Sets a regular expression character class which restricts the user input.E.g. [0-9] only allows numeric values. restrict The regular expression.
Referenced by game.gui.component.PlayerInputLinearFunction.getSubmitInput, game.gui.component.PlayerInputPoint.getSubmitInput, game.gui.component.PlayerInputPointDistance.getSubmitInput.