game::gui::component::PlayerInputLine
GraphicsContext game.gui.component.PlayerInputLine.gc
Point game.gui.component.PlayerInputLine.lineStart
Point game.gui.component.PlayerInputLine.lineEnd
Point game.gui.component.PlayerInputLine.cursor
Color game.gui.component.PlayerInputLine.lineColor
game.gui.component.PlayerInputLine.PlayerInputLine(GraphicsContext gc, Color lineColor)
void game.gui.component.PlayerInputLine.draw()
References game.gui.util.Draw2DHelper.drawCross.
Referenced by game.gui.level.AbstractLevelRenderer.redraw, game.gui.level.LevelRenderer1.draw.
void game.gui.component.PlayerInputLine.resetInput()
Point game.gui.component.PlayerInputLine.getNormalizedStartPoint()
References game.gui.util.Draw2DHelper.normalizePoint.
Referenced by game.gui.component.PlayerInputLine.submitFunction.
Point game.gui.component.PlayerInputLine.getNormalizedEndPoint()
References game.gui.util.Draw2DHelper.normalizePoint.
Referenced by game.gui.component.PlayerInputLine.submitFunction.
void game.gui.component.PlayerInputLine.handle(MouseEvent event)
Node game.gui.component.PlayerInputLine.getSubmitInput(LevelController levelController)
References game.controller.LevelController.getLevel, game.level.AbstractLevel.getFunction, game.module.geometry.shape.LinearFunction.getSlope, game.module.geometry.shape.LinearFunction.getIntercept, game.module.math.Rational.getNum, game.module.math.Rational.getDen, game.controller.LevelController.onInputSubmit, game.gui.component.PlayerInputLine.submitFunction, game.gui.component.AlertBox.display.
SubmitObject<LinearFunction> game.gui.component.PlayerInputLine.submitFunction(LevelController levelController)
References game.gui.component.PlayerInputLine.getNormalizedStartPoint, game.gui.component.PlayerInputLine.getNormalizedEndPoint.
Referenced by game.gui.component.PlayerInputLine.getSubmitInput.
void game.gui.component.PlayerInputLine.onMouseClicked(MouseEvent event)
void game.gui.component.PlayerInputLine.onMouseMoved(MouseEvent event)
boolean game.gui.component.PlayerInputLine.canValidate()