game::gui::util::Draw2DHelper
static void game.gui.util.Draw2DHelper.drawCoordinateSpace(GraphicsContext gc, double tick)
Draws a coordinate space gc tick
References game.module.sprite.Asset.SKY, game.module.sprite.Asset.CLOUDS, game.module.sprite.Asset.SEA.
Referenced by game.gui.level.BackgroundRenderer.initializeBackground.
static void game.gui.util.Draw2DHelper.drawCross(GraphicsContext gc, Point p, Color color)
Draws a cross on point. gc p location of the point color color of the cross
References game.module.geometry.shape.Point.getX, game.module.geometry.shape.Point.getY.
Referenced by game.gui.component.PlayerInputLine.draw.
static Point game.gui.util.Draw2DHelper.convertPointToCanvas(double width, double height, Point p)
Draws a cross on point. gc p location of the point color color of the cross
References game.module.geometry.shape.Point.getX, game.module.geometry.shape.Point.getY.
Referenced by game.gui.level.LevelAnimationRenderer1.startAnimation, game.gui.level.LevelAnimationRenderer2.startAnimation, game.gui.level.LevelAnimationRenderer3.startAnimation, game.gui.level.LevelAnimationRenderer4.startAnimation.
static Point game.gui.util.Draw2DHelper.pointToCoordinate(double width, double height, Point p)
Calculates a coordinate on the coordinate space by the cell size, width and height of the parent element width of the parent element height of the parent element p
References game.module.geometry.shape.Point.getX, game.module.geometry.shape.Point.getY.
static void game.gui.util.Draw2DHelper.drawLine(GraphicsContext gc, Point from, Point to, Color color)
Draws a line gc from starting position to end position color
References game.module.geometry.shape.Point.getX, game.module.geometry.shape.Point.getY.
Referenced by game.gui.level.LevelRenderer3.draw.
static void game.gui.util.Draw2DHelper.drawImage(GraphicsContext gc, Point p, Image image)
Draws an image gc p position of the image image the image
References game.module.geometry.shape.Point.getX, game.module.geometry.shape.Point.getY.
Referenced by game.gui.level.LevelRenderer2.draw, game.gui.level.LevelRenderer3.draw.
static void game.gui.util.Draw2DHelper.drawImage(GraphicsContext gc, Point p, Image image, double imageSize)
Draws an image gc p position of the image image the image imageSize size of the image
References game.module.geometry.shape.Point.getX, game.module.geometry.shape.Point.getY.
static Point game.gui.util.Draw2DHelper.pointToCoordinate(GraphicsContext gc, double x, double y)
method to get a Point by two doubles to help rendering a single location on a coordinate space gc x y
static Point game.gui.util.Draw2DHelper.pointToCoordinate(GraphicsContext gc, Point p)
method to get a Point by two doubles to help rendering a single location on a coordinate space gc p
References game.gui.util.Draw2DHelper.intToX, game.module.geometry.shape.Point.getX, game.gui.util.Draw2DHelper.intToY, game.module.geometry.shape.Point.getY.
static int game.gui.util.Draw2DHelper.intToY(GraphicsContext gc, int y)
method to get a Point by two doubles to help rendering a single location on a coordinate space gc y
Referenced by game.gui.util.Draw2DHelper.pointToCoordinate.
static int game.gui.util.Draw2DHelper.intToX(GraphicsContext gc, int x)
method to get a Point by two doubles to help rendering a single location on a coordinate space gc x
Referenced by game.gui.util.Draw2DHelper.pointToCoordinate.
static int game.gui.util.Draw2DHelper.normalizeX(int x)
Referenced by game.gui.util.Draw2DHelper.normalizePoint.
static int game.gui.util.Draw2DHelper.normalizeY(int y)
Referenced by game.gui.util.Draw2DHelper.normalizePoint.
static int game.gui.util.Draw2DHelper.denormalizeY(int y)
Referenced by game.gui.util.Draw2DHelper.denormalizePoint.
static Point game.gui.util.Draw2DHelper.normalizePoint(Point p)
References game.gui.util.Draw2DHelper.normalizeX, game.module.geometry.shape.Point.getX, game.gui.util.Draw2DHelper.normalizeY, game.module.geometry.shape.Point.getY.
Referenced by game.gui.component.PlayerInputLine.getNormalizedStartPoint, game.gui.component.PlayerInputLine.getNormalizedEndPoint.
static Point game.gui.util.Draw2DHelper.denormalizePoint(Point p)
References game.module.geometry.shape.Point.getX, game.gui.util.Draw2DHelper.denormalizeY, game.module.geometry.shape.Point.getY.
Referenced by game.gui.level.LevelAnimationRenderer1.startAnimation, game.gui.level.LevelAnimationRenderer2.startAnimation, game.gui.level.LevelAnimationRenderer3.startAnimation, game.gui.level.LevelAnimationRenderer4.startAnimation, game.gui.level.LevelRenderer2.draw, game.gui.level.LevelRenderer3.draw.
static int game.gui.util.Draw2DHelper.denormalizeX(int x)