game::gui::level::AbstractLevelRenderer
boolean game.gui.level.AbstractLevelRenderer.showHelperLine
final int game.gui.level.AbstractLevelRenderer.CELL_SIZE
Referenced by game.gui.level.LevelAnimationRenderer3.startAnimation, game.gui.level.LevelRenderer3.draw, game.level.FunctionGeneratorConfig.FunctionGeneratorConfig, game.level.Level1.Level1.
boolean game.gui.level.AbstractLevelRenderer.canValidate
PlayerInputLine game.gui.level.AbstractLevelRenderer.lineHelper
boolean game.gui.level.AbstractLevelRenderer.drawAfterInput
LinearFunction game.gui.level.AbstractLevelRenderer.currentFunction
game.gui.level.AbstractLevelRenderer.AbstractLevelRenderer()
Constructor initializes the coordinate system
References game.gui.level.AbstractLevelRenderer.redraw.
void game.gui.level.AbstractLevelRenderer.redraw()
References game.gui.level.LevelRenderer.draw, game.gui.component.PlayerInputLine.draw.
Referenced by game.controller.LevelController.onInputSubmit, game.gui.level.AbstractLevelRenderer.AbstractLevelRenderer.
void game.gui.level.AbstractLevelRenderer.setShowHelperLine(boolean showHelperLine)
Referenced by game.gui.level.LevelRenderer2.LevelRenderer2, game.gui.level.LevelRenderer3.LevelRenderer3, game.gui.level.LevelRenderer4.LevelRenderer4.
void game.gui.level.AbstractLevelRenderer.setCurrentFunction(LinearFunction currentFunction)
boolean game.gui.level.AbstractLevelRenderer.isResizable()
double game.gui.level.AbstractLevelRenderer.prefWidth(double height)
double game.gui.level.AbstractLevelRenderer.prefHeight(double width)
LinearFunction game.gui.level.AbstractLevelRenderer.getCurrentFunction()