game::gui::level::BackgroundRenderer
Transition game.gui.level.BackgroundRenderer.coordinateSpaceTransition
LevelAnimationRenderer game.gui.level.BackgroundRenderer.animation
game.gui.level.BackgroundRenderer.BackgroundRenderer()
void game.gui.level.BackgroundRenderer.initializeBackground()
References game.gui.util.Draw2DHelper.drawCoordinateSpace.
Referenced by game.controller.LevelController.LevelController.
void game.gui.level.BackgroundRenderer.stopBackgroundAnimation()
void game.gui.level.BackgroundRenderer.setAnimation(LevelAnimationRenderer animation)
void game.gui.level.BackgroundRenderer.startAnimation()
References game.gui.level.LevelAnimationRenderer.startAnimation.
Referenced by game.controller.LevelController.onInputSubmit.
void game.gui.level.BackgroundRenderer.stopAnimation()
References game.gui.level.LevelAnimationRenderer.stopAnimation.
Referenced by game.controller.LevelController.onInputSubmit.
boolean game.gui.level.BackgroundRenderer.isResizable()
double game.gui.level.BackgroundRenderer.prefWidth(double height)
double game.gui.level.BackgroundRenderer.prefHeight(double width)