game::level::Level
boolean game.level.Level.validate(SubmitObject submit)
int game.level.Level.getWinCondition()
Referenced by game.controller.LevelController.onInputSubmit.
Node game.level.Level.getDescription()
Referenced by game.controller.GameController.GameController, game.controller.GameController.onLevelCompleted, game.gui.Client.start.
Node game.level.Level.getBriefing()
LevelState game.level.Level.getCurrentState()
Referenced by game.controller.GameController.GameController, game.controller.GameController.onLevelCompleted, game.controller.LevelController.onInputSubmit.
LevelState game.level.Level.getNextLevelState()
Referenced by game.controller.LevelController.onInputSubmit.