.TH "C:/Bitbucket/uboote/uboote/client/LaserPiratesClient Directory Reference" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Bitbucket/uboote/uboote/client/LaserPiratesClient Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBsrc\fP"
.br
.in -1c
