.TH "game.gui.level.LevelRenderer1" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.gui.level.LevelRenderer1
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgame\&.gui\&.level\&.AbstractLevelRenderer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLevelRenderer1\fP ()"
.br
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.ti -1c
.RI "void \fBsetPlayerInputLine\fP (\fBPlayerInputLine\fP lineInput)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 17 of file LevelRenderer1\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "game\&.gui\&.level\&.LevelRenderer1\&.LevelRenderer1 ()"

.PP
Definition at line 21 of file LevelRenderer1\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void game\&.gui\&.level\&.LevelRenderer1\&.draw ()"
This is always called 
.PP
Implements \fBgame\&.gui\&.level\&.LevelRenderer\fP\&.
.PP
Definition at line 26 of file LevelRenderer1\&.java\&.
.SS "void game\&.gui\&.level\&.LevelRenderer1\&.setPlayerInputLine (\fBPlayerInputLine\fP lineInput)"

.PP
Definition at line 31 of file LevelRenderer1\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
