.TH "game.Main" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.Main
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Nothing to see here\&. Just launches the client 
.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 12 of file Main\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void game\&.Main\&.main (String [] args)\fC [static]\fP"

.PP
Definition at line 14 of file Main\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
