.TH "game.gui.component.LevelIntroBox" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.gui.component.LevelIntroBox
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBdisplay\fP (Node message)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A box which is used for displaying level information for the player which can only be closed by clicking on the ok button\&. 
.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 20 of file LevelIntroBox\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void game\&.gui\&.component\&.LevelIntroBox\&.display (Node message)\fC [static]\fP"

.PP
\fBParameters:\fP
.RS 4
\fItitle\fP 
.br
\fImessage\fP 
.RE
.PP

.PP
Definition at line 28 of file LevelIntroBox\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
