.TH "game.gui.Client" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.gui.Client
.SH SYNOPSIS
.br
.PP
.PP
Inherits Application\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBstart\fP (Stage primaryStage)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBlaunchClient\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The client application which sets up the menu bar and the GameController\&. The game itself is completely encapsulated in the GameController\&. 
.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 27 of file Client\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void game\&.gui\&.Client\&.launchClient (String [] args)\fC [static]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIargs\fP the command line arguments 
.RE
.PP

.PP
Definition at line 114 of file Client\&.java\&.
.SS "void game\&.gui\&.Client\&.start (Stage primaryStage)"

.PP
Definition at line 32 of file Client\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
