.TH "game.gui.component.AbstractPlayerInput" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.gui.component.AbstractPlayerInput
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgame\&.gui\&.component\&.PlayerInput\fP, and EventHandler< MouseEvent >\&.
.PP
Inherited by \fBgame\&.gui\&.component\&.PlayerInputLine\fP, \fBgame\&.gui\&.component\&.PlayerInputLinearFunction\fP, and \fBgame\&.gui\&.component\&.PlayerInputPoint\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The base class for all player inputs 
.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 12 of file AbstractPlayerInput\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
