.TH "game.gui.component.PlayerInputLinearFunction" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.gui.component.PlayerInputLinearFunction
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgame\&.gui\&.component\&.AbstractPlayerInput\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.ti -1c
.RI "void \fBhandle\fP (MouseEvent event)"
.br
.ti -1c
.RI "Node \fBgetSubmitInput\fP (\fBLevelController\fP levelController)"
.br
.ti -1c
.RI "\fBSubmitObject\fP< \fBLinearFunction\fP > \fBsubmitFunction\fP (\fBLevelController\fP levelController)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 20 of file PlayerInputLinearFunction\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void game\&.gui\&.component\&.PlayerInputLinearFunction\&.draw ()"

.PP
Implements \fBgame\&.gui\&.component\&.PlayerInput\fP\&.
.PP
Definition at line 26 of file PlayerInputLinearFunction\&.java\&.
.SS "Node game\&.gui\&.component\&.PlayerInputLinearFunction\&.getSubmitInput (\fBLevelController\fP levelController)"

.PP
Implements \fBgame\&.gui\&.component\&.PlayerInput\fP\&.
.PP
Definition at line 35 of file PlayerInputLinearFunction\&.java\&.
.SS "void game\&.gui\&.component\&.PlayerInputLinearFunction\&.handle (MouseEvent event)"

.PP
Definition at line 31 of file PlayerInputLinearFunction\&.java\&.
.SS "\fBSubmitObject\fP<\fBLinearFunction\fP> game\&.gui\&.component\&.PlayerInputLinearFunction\&.submitFunction (\fBLevelController\fP levelController)"

.PP
Implements \fBgame\&.gui\&.component\&.PlayerInput\fP\&.
.PP
Definition at line 94 of file PlayerInputLinearFunction\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
