.TH "game.level.Level" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.level.Level
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBgame\&.level\&.AbstractLevel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBvalidate\fP (\fBSubmitObject\fP submit)"
.br
.ti -1c
.RI "int \fBgetWinCondition\fP ()"
.br
.ti -1c
.RI "Node \fBgetDescription\fP ()"
.br
.ti -1c
.RI "Node \fBgetBriefing\fP ()"
.br
.ti -1c
.RI "\fBLevelState\fP \fBgetCurrentState\fP ()"
.br
.ti -1c
.RI "\fBLevelState\fP \fBgetNextLevelState\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 9 of file Level\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Node game\&.level\&.Level\&.getBriefing ()"

.PP
Implemented in \fBgame\&.level\&.AbstractLevel\fP, \fBgame\&.level\&.Level3\fP, \fBgame\&.level\&.Level2\fP, \fBgame\&.level\&.Level1\fP, and \fBgame\&.level\&.Level4\fP\&.
.SS "\fBLevelState\fP game\&.level\&.Level\&.getCurrentState ()"

.PP
Implemented in \fBgame\&.level\&.Level1\fP, \fBgame\&.level\&.Level4\fP, \fBgame\&.level\&.Level3\fP, and \fBgame\&.level\&.Level2\fP\&.
.SS "Node game\&.level\&.Level\&.getDescription ()"

.PP
Implemented in \fBgame\&.level\&.Level3\fP, \fBgame\&.level\&.Level2\fP, \fBgame\&.level\&.Level1\fP, and \fBgame\&.level\&.Level4\fP\&.
.SS "\fBLevelState\fP game\&.level\&.Level\&.getNextLevelState ()"

.PP
Implemented in \fBgame\&.level\&.Level1\fP, \fBgame\&.level\&.Level4\fP, \fBgame\&.level\&.Level3\fP, and \fBgame\&.level\&.Level2\fP\&.
.SS "int game\&.level\&.Level\&.getWinCondition ()"

.PP
Implemented in \fBgame\&.level\&.Level1\fP, \fBgame\&.level\&.Level3\fP, \fBgame\&.level\&.Level2\fP, and \fBgame\&.level\&.Level4\fP\&.
.SS "boolean game\&.level\&.Level\&.validate (\fBSubmitObject\fP submit)"

.PP
Implemented in \fBgame\&.level\&.AbstractLevel\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
