.TH "game.module.sprite" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.module.sprite
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAsset\fP"
.br
.ti -1c
.RI "class \fBSprite\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
