.TH "game.gui.component.ConfirmBox" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.gui.component.ConfirmBox
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Boolean \fBdisplay\fP (String title, String message)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A \fBConfirmBox\fP is used, when you need to ask for the user´s decision\&. If yes is clicked, the method \fBdisplay()\fP returns true, which then the developer can use to execute code based on that decision 
.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 19 of file ConfirmBox\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static Boolean game\&.gui\&.component\&.ConfirmBox\&.display (String title, String message)\fC [static]\fP"

.PP
\fBParameters:\fP
.RS 4
\fItitle\fP 
.br
\fImessage\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
Boolean 
.RE
.PP

.PP
Definition at line 30 of file ConfirmBox\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
