.TH "game.gui.level.LevelRenderer3" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.gui.level.LevelRenderer3
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgame\&.gui\&.level\&.AbstractLevelRenderer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLevelRenderer3\fP (\fBLinearFunction\fP currentLevelFunction)"
.br
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 18 of file LevelRenderer3\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "game\&.gui\&.level\&.LevelRenderer3\&.LevelRenderer3 (\fBLinearFunction\fP currentLevelFunction)"

.PP
Definition at line 22 of file LevelRenderer3\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void game\&.gui\&.level\&.LevelRenderer3\&.draw ()"
This is always called 
.PP
Implements \fBgame\&.gui\&.level\&.LevelRenderer\fP\&.
.PP
Definition at line 29 of file LevelRenderer3\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
