.TH "game.gui.component.PlayerInput" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.gui.component.PlayerInput
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBgame\&.gui\&.component\&.AbstractPlayerInput\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.ti -1c
.RI "Node \fBgetSubmitInput\fP (\fBLevelController\fP controller)"
.br
.ti -1c
.RI "\fBSubmitObject\fP \fBsubmitFunction\fP (\fBLevelController\fP levelController)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBPlayerInput\fP interface 
.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 11 of file PlayerInput\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void game\&.gui\&.component\&.PlayerInput\&.draw ()"

.PP
Implemented in \fBgame\&.gui\&.component\&.PlayerInputLine\fP, \fBgame\&.gui\&.component\&.PlayerInputLinearFunction\fP, and \fBgame\&.gui\&.component\&.PlayerInputPoint\fP\&.
.SS "Node game\&.gui\&.component\&.PlayerInput\&.getSubmitInput (\fBLevelController\fP controller)"

.PP
Implemented in \fBgame\&.gui\&.component\&.PlayerInputLine\fP, \fBgame\&.gui\&.component\&.PlayerInputLinearFunction\fP, \fBgame\&.gui\&.component\&.PlayerInputPoint\fP, and \fBgame\&.gui\&.component\&.PlayerInputPointDistance\fP\&.
.SS "\fBSubmitObject\fP game\&.gui\&.component\&.PlayerInput\&.submitFunction (\fBLevelController\fP levelController)"

.PP
Implemented in \fBgame\&.gui\&.component\&.PlayerInputLine\fP, \fBgame\&.gui\&.component\&.PlayerInputLinearFunction\fP, \fBgame\&.gui\&.component\&.PlayerInputPointDistance\fP, and \fBgame\&.gui\&.component\&.PlayerInputPointDepth\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
