.TH "game.level.SubmitType" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.level.SubmitType
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPOINT\fP"
.br
.ti -1c
.RI "\fBFUNCTION\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 9 of file SubmitType\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "game\&.level\&.SubmitType\&.FUNCTION"

.PP
Definition at line 11 of file SubmitType\&.java\&.
.SS "game\&.level\&.SubmitType\&.POINT"

.PP
Definition at line 10 of file SubmitType\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
