.TH "game.level.Level3" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.level.Level3
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgame\&.level\&.AbstractLevel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLevel3\fP ()"
.br
.ti -1c
.RI "int \fBgetWinCondition\fP ()"
.br
.ti -1c
.RI "\fBLevelState\fP \fBgetCurrentState\fP ()"
.br
.ti -1c
.RI "\fBLevelState\fP \fBgetNextLevelState\fP ()"
.br
.ti -1c
.RI "Node \fBgetDescription\fP ()"
.br
.ti -1c
.RI "Node \fBgetBriefing\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 17 of file Level3\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "game\&.level\&.Level3\&.Level3 ()"

.PP
Definition at line 19 of file Level3\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Node game\&.level\&.Level3\&.getBriefing ()"

.PP
Implements \fBgame\&.level\&.Level\fP\&.
.PP
Definition at line 86 of file Level3\&.java\&.
.SS "\fBLevelState\fP game\&.level\&.Level3\&.getCurrentState ()"

.PP
Implements \fBgame\&.level\&.Level\fP\&.
.PP
Definition at line 42 of file Level3\&.java\&.
.SS "Node game\&.level\&.Level3\&.getDescription ()"

.PP
Implements \fBgame\&.level\&.Level\fP\&.
.PP
Definition at line 52 of file Level3\&.java\&.
.SS "\fBLevelState\fP game\&.level\&.Level3\&.getNextLevelState ()"

.PP
Implements \fBgame\&.level\&.Level\fP\&.
.PP
Definition at line 47 of file Level3\&.java\&.
.SS "int game\&.level\&.Level3\&.getWinCondition ()"

.PP
Implements \fBgame\&.level\&.Level\fP\&.
.PP
Definition at line 37 of file Level3\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
