.TH "game.module.sprite.Asset" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.module.sprite.Asset
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fBSEA\fP = 'asset/sea\&.png'"
.br
.ti -1c
.RI "static final String \fBSKY\fP = 'asset/sky\&.png'"
.br
.ti -1c
.RI "static final String \fBCLOUDS\fP = 'asset/clouds\&.png'"
.br
.ti -1c
.RI "static final String \fBADMIRAL\fP = 'asset/Admiral\&.gif'"
.br
.ti -1c
.RI "static final String \fBSATELLITE\fP = 'asset/satellite\&.png'"
.br
.ti -1c
.RI "static final String \fBPLANE\fP = 'asset/plane\&.png'"
.br
.ti -1c
.RI "static final String \fBPLANE_R\fP = 'asset/plane_right\&.png'"
.br
.ti -1c
.RI "static final String \fBSUBMARINE\fP = 'asset/submarine\&.png'"
.br
.ti -1c
.RI "static final String \fBSUBMARINE_R\fP = 'asset/submarine_right\&.png'"
.br
.ti -1c
.RI "static final String \fBCRUISER\fP = 'asset/cruiser\&.png'"
.br
.ti -1c
.RI "static final String \fBCRUISER_R\fP = 'asset/cruiser_right\&.png'"
.br
.ti -1c
.RI "static final String \fBEXPLOSION\fP = 'asset/explosion\&.png'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 7 of file Asset\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String game\&.module\&.sprite\&.Asset\&.ADMIRAL = 'asset/Admiral\&.gif'\fC [static]\fP"

.PP
Definition at line 11 of file Asset\&.java\&.
.SS "final String game\&.module\&.sprite\&.Asset\&.CLOUDS = 'asset/clouds\&.png'\fC [static]\fP"

.PP
Definition at line 10 of file Asset\&.java\&.
.SS "final String game\&.module\&.sprite\&.Asset\&.CRUISER = 'asset/cruiser\&.png'\fC [static]\fP"

.PP
Definition at line 17 of file Asset\&.java\&.
.SS "final String game\&.module\&.sprite\&.Asset\&.CRUISER_R = 'asset/cruiser_right\&.png'\fC [static]\fP"

.PP
Definition at line 18 of file Asset\&.java\&.
.SS "final String game\&.module\&.sprite\&.Asset\&.EXPLOSION = 'asset/explosion\&.png'\fC [static]\fP"

.PP
Definition at line 19 of file Asset\&.java\&.
.SS "final String game\&.module\&.sprite\&.Asset\&.PLANE = 'asset/plane\&.png'\fC [static]\fP"

.PP
Definition at line 13 of file Asset\&.java\&.
.SS "final String game\&.module\&.sprite\&.Asset\&.PLANE_R = 'asset/plane_right\&.png'\fC [static]\fP"

.PP
Definition at line 14 of file Asset\&.java\&.
.SS "final String game\&.module\&.sprite\&.Asset\&.SATELLITE = 'asset/satellite\&.png'\fC [static]\fP"

.PP
Definition at line 12 of file Asset\&.java\&.
.SS "final String game\&.module\&.sprite\&.Asset\&.SEA = 'asset/sea\&.png'\fC [static]\fP"

.PP
Definition at line 8 of file Asset\&.java\&.
.SS "final String game\&.module\&.sprite\&.Asset\&.SKY = 'asset/sky\&.png'\fC [static]\fP"

.PP
Definition at line 9 of file Asset\&.java\&.
.SS "final String game\&.module\&.sprite\&.Asset\&.SUBMARINE = 'asset/submarine\&.png'\fC [static]\fP"

.PP
Definition at line 15 of file Asset\&.java\&.
.SS "final String game\&.module\&.sprite\&.Asset\&.SUBMARINE_R = 'asset/submarine_right\&.png'\fC [static]\fP"

.PP
Definition at line 16 of file Asset\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
