.TH "game.gui.level.LevelAnimationRenderer1" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.gui.level.LevelAnimationRenderer1
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgame\&.gui\&.level\&.LevelAnimationRenderer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLevelAnimationRenderer1\fP (Canvas canvas)"
.br
.ti -1c
.RI "void \fBstartAnimation\fP (Canvas canvas)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBstopAnimation\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 26 of file LevelAnimationRenderer1\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "game\&.gui\&.level\&.LevelAnimationRenderer1\&.LevelAnimationRenderer1 (Canvas canvas)"

.PP
Definition at line 29 of file LevelAnimationRenderer1\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void game\&.gui\&.level\&.LevelAnimationRenderer1\&.startAnimation (Canvas canvas)"

.PP
Definition at line 34 of file LevelAnimationRenderer1\&.java\&.
.SS "void game\&.gui\&.level\&.LevelAnimationRenderer1\&.stopAnimation ()\fC [protected]\fP"

.PP
Definition at line 76 of file LevelAnimationRenderer1\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
