.TH "game.gui.level.BackgroundRenderer" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.gui.level.BackgroundRenderer
.SH SYNOPSIS
.br
.PP
.PP
Inherits Canvas\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBackgroundRenderer\fP ()"
.br
.ti -1c
.RI "void \fBinitializeBackground\fP ()"
.br
.ti -1c
.RI "void \fBstopBackgroundAnimation\fP ()"
.br
.ti -1c
.RI "void \fBsetAnimation\fP (\fBLevelAnimationRenderer\fP animation)"
.br
.ti -1c
.RI "void \fBstartAnimation\fP ()"
.br
.ti -1c
.RI "void \fBstopAnimation\fP ()"
.br
.ti -1c
.RI "boolean \fBisResizable\fP ()"
.br
.ti -1c
.RI "double \fBprefWidth\fP (double height)"
.br
.ti -1c
.RI "double \fBprefHeight\fP (double width)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 15 of file BackgroundRenderer\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "game\&.gui\&.level\&.BackgroundRenderer\&.BackgroundRenderer ()"

.PP
Definition at line 20 of file BackgroundRenderer\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void game\&.gui\&.level\&.BackgroundRenderer\&.initializeBackground ()"

.PP
Definition at line 24 of file BackgroundRenderer\&.java\&.
.SS "boolean game\&.gui\&.level\&.BackgroundRenderer\&.isResizable ()"

.PP
Definition at line 60 of file BackgroundRenderer\&.java\&.
.SS "double game\&.gui\&.level\&.BackgroundRenderer\&.prefHeight (double width)"

.PP
Definition at line 70 of file BackgroundRenderer\&.java\&.
.SS "double game\&.gui\&.level\&.BackgroundRenderer\&.prefWidth (double height)"

.PP
Definition at line 65 of file BackgroundRenderer\&.java\&.
.SS "void game\&.gui\&.level\&.BackgroundRenderer\&.setAnimation (\fBLevelAnimationRenderer\fP animation)"

.PP
Definition at line 46 of file BackgroundRenderer\&.java\&.
.SS "void game\&.gui\&.level\&.BackgroundRenderer\&.startAnimation ()"

.PP
Definition at line 50 of file BackgroundRenderer\&.java\&.
.SS "void game\&.gui\&.level\&.BackgroundRenderer\&.stopAnimation ()"

.PP
Definition at line 55 of file BackgroundRenderer\&.java\&.
.SS "void game\&.gui\&.level\&.BackgroundRenderer\&.stopBackgroundAnimation ()"

.PP
Definition at line 42 of file BackgroundRenderer\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
