.TH "game.level.Level1" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.level.Level1
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgame\&.level\&.AbstractLevel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLevel1\fP ()"
.br
.ti -1c
.RI "int \fBgetWinCondition\fP ()"
.br
.ti -1c
.RI "Node \fBgetDescription\fP ()"
.br
.ti -1c
.RI "Node \fBgetBriefing\fP ()"
.br
.ti -1c
.RI "\fBLevelState\fP \fBgetCurrentState\fP ()"
.br
.ti -1c
.RI "\fBLevelState\fP \fBgetNextLevelState\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 22 of file Level1\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "game\&.level\&.Level1\&.Level1 ()"

.PP
Definition at line 24 of file Level1\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Node game\&.level\&.Level1\&.getBriefing ()"

.PP
Implements \fBgame\&.level\&.Level\fP\&.
.PP
Definition at line 72 of file Level1\&.java\&.
.SS "\fBLevelState\fP game\&.level\&.Level1\&.getCurrentState ()"

.PP
Implements \fBgame\&.level\&.Level\fP\&.
.PP
Definition at line 78 of file Level1\&.java\&.
.SS "Node game\&.level\&.Level1\&.getDescription ()"

.PP
Implements \fBgame\&.level\&.Level\fP\&.
.PP
Definition at line 44 of file Level1\&.java\&.
.SS "\fBLevelState\fP game\&.level\&.Level1\&.getNextLevelState ()"

.PP
Implements \fBgame\&.level\&.Level\fP\&.
.PP
Definition at line 83 of file Level1\&.java\&.
.SS "int game\&.level\&.Level1\&.getWinCondition ()"

.PP
Implements \fBgame\&.level\&.Level\fP\&.
.PP
Definition at line 39 of file Level1\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
