.TH "game.gui.component.PlayerInputPoint" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.gui.component.PlayerInputPoint
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgame\&.gui\&.component\&.AbstractPlayerInput\fP\&.
.PP
Inherited by \fBgame\&.gui\&.component\&.PlayerInputPointDepth\fP, and \fBgame\&.gui\&.component\&.PlayerInputPointDistance\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.ti -1c
.RI "void \fBhandle\fP (MouseEvent event)"
.br
.ti -1c
.RI "Node \fBgetSubmitInput\fP (\fBLevelController\fP levelController)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBNumberFieldInput\fP \fBgetFieldInput\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A \fC\fBPlayerInputLine\fP\fP 
.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 18 of file PlayerInputPoint\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void game\&.gui\&.component\&.PlayerInputPoint\&.draw ()"

.PP
Implements \fBgame\&.gui\&.component\&.PlayerInput\fP\&.
.PP
Definition at line 23 of file PlayerInputPoint\&.java\&.
.SS "\fBNumberFieldInput\fP game\&.gui\&.component\&.PlayerInputPoint\&.getFieldInput ()\fC [protected]\fP"

.PP
Definition at line 69 of file PlayerInputPoint\&.java\&.
.SS "Node game\&.gui\&.component\&.PlayerInputPoint\&.getSubmitInput (\fBLevelController\fP levelController)"

.PP
Implements \fBgame\&.gui\&.component\&.PlayerInput\fP\&.
.PP
Definition at line 32 of file PlayerInputPoint\&.java\&.
.SS "void game\&.gui\&.component\&.PlayerInputPoint\&.handle (MouseEvent event)"

.PP
Definition at line 28 of file PlayerInputPoint\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
