.TH "game.gui.debug.DebugGroup" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.gui.debug.DebugGroup
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBdisplay\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 25 of file DebugGroup\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void game\&.gui\&.debug\&.DebugGroup\&.display ()\fC [static]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIparentWindow\fP 
.RE
.PP

.PP
Definition at line 33 of file DebugGroup\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
