.TH "game.gui.component.StatusMessageType" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.gui.component.StatusMessageType
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTYPE_CORRECT\fP"
.br
.ti -1c
.RI "\fBTYPE_WRONG\fP"
.br
.ti -1c
.RI "\fBTYPE_NEUTRAL\fP"
.br
.ti -1c
.RI "\fBTYPE_PROCEED_ON_WAIT\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 7 of file StatusMessageType\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "game\&.gui\&.component\&.StatusMessageType\&.TYPE_CORRECT"

.PP
Definition at line 8 of file StatusMessageType\&.java\&.
.SS "game\&.gui\&.component\&.StatusMessageType\&.TYPE_NEUTRAL"

.PP
Definition at line 10 of file StatusMessageType\&.java\&.
.SS "game\&.gui\&.component\&.StatusMessageType\&.TYPE_PROCEED_ON_WAIT"

.PP
Definition at line 11 of file StatusMessageType\&.java\&.
.SS "game\&.gui\&.component\&.StatusMessageType\&.TYPE_WRONG"

.PP
Definition at line 9 of file StatusMessageType\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
