.TH "game.gui.component.PlayerInputPointDistance" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.gui.component.PlayerInputPointDistance
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgame\&.gui\&.component\&.PlayerInputPoint\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Node \fBgetSubmitInput\fP (\fBLevelController\fP levelController)"
.br
.ti -1c
.RI "\fBSubmitObject\fP< \fBPoint\fP > \fBsubmitFunction\fP (\fBLevelController\fP levelController)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBNumberFieldInput\fP \fBgetFieldInput\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 19 of file PlayerInputPointDistance\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBNumberFieldInput\fP game\&.gui\&.component\&.PlayerInputPointDistance\&.getFieldInput ()\fC [protected]\fP"

.PP
Definition at line 71 of file PlayerInputPointDistance\&.java\&.
.SS "Node game\&.gui\&.component\&.PlayerInputPointDistance\&.getSubmitInput (\fBLevelController\fP levelController)"

.PP
Implements \fBgame\&.gui\&.component\&.PlayerInput\fP\&.
.PP
Definition at line 25 of file PlayerInputPointDistance\&.java\&.
.SS "\fBSubmitObject\fP<\fBPoint\fP> game\&.gui\&.component\&.PlayerInputPointDistance\&.submitFunction (\fBLevelController\fP levelController)"

.PP
Implements \fBgame\&.gui\&.component\&.PlayerInput\fP\&.
.PP
Definition at line 62 of file PlayerInputPointDistance\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
