.TH "game.level.FunctionGeneratorConfig" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.level.FunctionGeneratorConfig
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFunctionGeneratorConfig\fP ()"
.br
.ti -1c
.RI "int \fBgetMaxValue\fP ()"
.br
.ti -1c
.RI "void \fBsetMaxValue\fP (int max)"
.br
.ti -1c
.RI "void \fBsetAx\fP (int ax)"
.br
.ti -1c
.RI "void \fBsetAy\fP (int ay)"
.br
.ti -1c
.RI "void \fBsetBx\fP (int bx)"
.br
.ti -1c
.RI "void \fBsetBy\fP (int by)"
.br
.ti -1c
.RI "int \fBgetAx\fP ()"
.br
.ti -1c
.RI "int \fBgetAy\fP ()"
.br
.ti -1c
.RI "int \fBgetBx\fP ()"
.br
.ti -1c
.RI "int \fBgetBy\fP ()"
.br
.ti -1c
.RI "void \fBsetMaxIntercept\fP (int maxIntercept)"
.br
.ti -1c
.RI "int \fBgetMaxIntercept\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 9 of file FunctionGeneratorConfig\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "game\&.level\&.FunctionGeneratorConfig\&.FunctionGeneratorConfig ()"

.PP
Definition at line 18 of file FunctionGeneratorConfig\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "int game\&.level\&.FunctionGeneratorConfig\&.getAx ()"

.PP
Definition at line 46 of file FunctionGeneratorConfig\&.java\&.
.SS "int game\&.level\&.FunctionGeneratorConfig\&.getAy ()"

.PP
Definition at line 50 of file FunctionGeneratorConfig\&.java\&.
.SS "int game\&.level\&.FunctionGeneratorConfig\&.getBx ()"

.PP
Definition at line 54 of file FunctionGeneratorConfig\&.java\&.
.SS "int game\&.level\&.FunctionGeneratorConfig\&.getBy ()"

.PP
Definition at line 58 of file FunctionGeneratorConfig\&.java\&.
.SS "int game\&.level\&.FunctionGeneratorConfig\&.getMaxIntercept ()"

.PP
Definition at line 66 of file FunctionGeneratorConfig\&.java\&.
.SS "int game\&.level\&.FunctionGeneratorConfig\&.getMaxValue ()"

.PP
Definition at line 22 of file FunctionGeneratorConfig\&.java\&.
.SS "void game\&.level\&.FunctionGeneratorConfig\&.setAx (int ax)"

.PP
Definition at line 30 of file FunctionGeneratorConfig\&.java\&.
.SS "void game\&.level\&.FunctionGeneratorConfig\&.setAy (int ay)"

.PP
Definition at line 34 of file FunctionGeneratorConfig\&.java\&.
.SS "void game\&.level\&.FunctionGeneratorConfig\&.setBx (int bx)"

.PP
Definition at line 38 of file FunctionGeneratorConfig\&.java\&.
.SS "void game\&.level\&.FunctionGeneratorConfig\&.setBy (int by)"

.PP
Definition at line 42 of file FunctionGeneratorConfig\&.java\&.
.SS "void game\&.level\&.FunctionGeneratorConfig\&.setMaxIntercept (int maxIntercept)"

.PP
Definition at line 62 of file FunctionGeneratorConfig\&.java\&.
.SS "void game\&.level\&.FunctionGeneratorConfig\&.setMaxValue (int max)"

.PP
Definition at line 26 of file FunctionGeneratorConfig\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
