.TH "game.level.Level2" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.level.Level2
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgame\&.level\&.AbstractLevel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLevel2\fP ()"
.br
.ti -1c
.RI "int \fBgetWinCondition\fP ()"
.br
.ti -1c
.RI "\fBLevelState\fP \fBgetCurrentState\fP ()"
.br
.ti -1c
.RI "\fBLevelState\fP \fBgetNextLevelState\fP ()"
.br
.ti -1c
.RI "Node \fBgetDescription\fP ()"
.br
.ti -1c
.RI "Node \fBgetBriefing\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 16 of file Level2\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "game\&.level\&.Level2\&.Level2 ()"

.PP
Definition at line 18 of file Level2\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Node game\&.level\&.Level2\&.getBriefing ()"

.PP
Implements \fBgame\&.level\&.Level\fP\&.
.PP
Definition at line 84 of file Level2\&.java\&.
.SS "\fBLevelState\fP game\&.level\&.Level2\&.getCurrentState ()"

.PP
Implements \fBgame\&.level\&.Level\fP\&.
.PP
Definition at line 41 of file Level2\&.java\&.
.SS "Node game\&.level\&.Level2\&.getDescription ()"

.PP
Implements \fBgame\&.level\&.Level\fP\&.
.PP
Definition at line 51 of file Level2\&.java\&.
.SS "\fBLevelState\fP game\&.level\&.Level2\&.getNextLevelState ()"

.PP
Implements \fBgame\&.level\&.Level\fP\&.
.PP
Definition at line 46 of file Level2\&.java\&.
.SS "int game\&.level\&.Level2\&.getWinCondition ()"

.PP
Implements \fBgame\&.level\&.Level\fP\&.
.PP
Definition at line 35 of file Level2\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
