.TH "game.level.SubmitObject< T >" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.level.SubmitObject< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSubmitObject\fP (T function)"
.br
.ti -1c
.RI "T \fBgetSubmit\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 10 of file SubmitObject\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBgame\&.level\&.SubmitObject\fP< T >\&.\fBSubmitObject\fP (T function)"

.PP
Definition at line 13 of file SubmitObject\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "T \fBgame\&.level\&.SubmitObject\fP< T >\&.getSubmit ()"

.PP
Definition at line 17 of file SubmitObject\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
