.TH "game.gui.level.LevelRenderer" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.gui.level.LevelRenderer
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBgame\&.gui\&.level\&.AbstractLevelRenderer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
interface for \fBLevelRenderer\fP objects 
.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 9 of file LevelRenderer\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void game\&.gui\&.level\&.LevelRenderer\&.draw ()"
This is always called 
.PP
Implemented in \fBgame\&.gui\&.level\&.LevelRenderer3\fP, \fBgame\&.gui\&.level\&.LevelRenderer2\fP, \fBgame\&.gui\&.level\&.LevelRenderer1\fP, and \fBgame\&.gui\&.level\&.LevelRenderer4\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
