.TH "game.gui.component.AlertBox" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.gui.component.AlertBox
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBdisplay\fP (String title, String message)"
.br
.in -1c
.SH "Detailed Description"
.PP 
An alert box which can be closed by clicking ok\&. It also blocks the client, as long the alert box is still open\&. 
.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 19 of file AlertBox\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void game\&.gui\&.component\&.AlertBox\&.display (String title, String message)\fC [static]\fP"

.PP
\fBParameters:\fP
.RS 4
\fItitle\fP 
.br
\fImessage\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
Boolean 
.RE
.PP

.PP
Definition at line 29 of file AlertBox\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
