.TH "game.gui.component.PlayerInputPointDepth" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.gui.component.PlayerInputPointDepth
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgame\&.gui\&.component\&.PlayerInputPoint\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSubmitObject\fP< \fBPoint\fP > \fBsubmitFunction\fP (\fBLevelController\fP levelController)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 11 of file PlayerInputPointDepth\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSubmitObject\fP<\fBPoint\fP> game\&.gui\&.component\&.PlayerInputPointDepth\&.submitFunction (\fBLevelController\fP levelController)"

.PP
Implements \fBgame\&.gui\&.component\&.PlayerInput\fP\&.
.PP
Definition at line 14 of file PlayerInputPointDepth\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
