.TH "game.level.Level4" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.level.Level4
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgame\&.level\&.AbstractLevel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLevel4\fP ()"
.br
.ti -1c
.RI "int \fBgetWinCondition\fP ()"
.br
.ti -1c
.RI "Node \fBgetDescription\fP ()"
.br
.ti -1c
.RI "Node \fBgetBriefing\fP ()"
.br
.ti -1c
.RI "\fBLevelState\fP \fBgetCurrentState\fP ()"
.br
.ti -1c
.RI "\fBLevelState\fP \fBgetNextLevelState\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 17 of file Level4\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "game\&.level\&.Level4\&.Level4 ()"

.PP
Definition at line 19 of file Level4\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Node game\&.level\&.Level4\&.getBriefing ()"

.PP
Implements \fBgame\&.level\&.Level\fP\&.
.PP
Definition at line 69 of file Level4\&.java\&.
.SS "\fBLevelState\fP game\&.level\&.Level4\&.getCurrentState ()"

.PP
Implements \fBgame\&.level\&.Level\fP\&.
.PP
Definition at line 76 of file Level4\&.java\&.
.SS "Node game\&.level\&.Level4\&.getDescription ()"

.PP
Implements \fBgame\&.level\&.Level\fP\&.
.PP
Definition at line 38 of file Level4\&.java\&.
.SS "\fBLevelState\fP game\&.level\&.Level4\&.getNextLevelState ()"

.PP
Implements \fBgame\&.level\&.Level\fP\&.
.PP
Definition at line 81 of file Level4\&.java\&.
.SS "int game\&.level\&.Level4\&.getWinCondition ()"

.PP
Implements \fBgame\&.level\&.Level\fP\&.
.PP
Definition at line 33 of file Level4\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
