.TH "game.level.LinearFunctionGenerator" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.level.LinearFunctionGenerator
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBLinearFunction\fP \fBgenerateLinearFunction\fP (\fBFunctionGeneratorConfig\fP config)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Helper Class for generating linear functions randomly\&. For example:
.br
 \fCLinearFunction linearFunction = LinearFunctionGenerator\&.generateLinearFunction(40);\fP
.br
 generates a valid linear function ranging from -20 to 20 in the x and y axis\&.
.br
 The method call 
.br
 \fCLinearFunction linearFunction = LinearFunctionGenerator\&.generateLinearFunction(20);\fP
.br
 generates a valid linear function ranging from -10 to 10 in the x and y axis\&. 
.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 18 of file LinearFunctionGenerator\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBLinearFunction\fP game\&.level\&.LinearFunctionGenerator\&.generateLinearFunction (\fBFunctionGeneratorConfig\fP config)\fC [static]\fP"
\fCgenerateLinearFunction\fP generates linear functions randomly\&. 
.PP
\fBParameters:\fP
.RS 4
\fIconfig\fP Configurator for the function 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 25 of file LinearFunctionGenerator\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
