.TH "game.gui.level.LevelAnimationRenderer" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.gui.level.LevelAnimationRenderer
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBgame\&.gui\&.level\&.LevelAnimationRenderer1\fP, \fBgame\&.gui\&.level\&.LevelAnimationRenderer2\fP, \fBgame\&.gui\&.level\&.LevelAnimationRenderer3\fP, and \fBgame\&.gui\&.level\&.LevelAnimationRenderer4\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLevelAnimationRenderer\fP (Canvas canvas)"
.br
.ti -1c
.RI "abstract void \fBstartAnimation\fP (Canvas canvas)"
.br
.ti -1c
.RI "void \fBsetCurrentFunction\fP (\fBLinearFunction\fP currentFunction)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "abstract void \fBstopAnimation\fP ()"
.br
.ti -1c
.RI "\fBLinearFunction\fP \fBgetCurrentFunction\fP ()"
.br
.ti -1c
.RI "Pane \fBgetAnimationWrapper\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 14 of file LevelAnimationRenderer\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "game\&.gui\&.level\&.LevelAnimationRenderer\&.LevelAnimationRenderer (Canvas canvas)"

.PP
Definition at line 18 of file LevelAnimationRenderer\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Pane game\&.gui\&.level\&.LevelAnimationRenderer\&.getAnimationWrapper ()\fC [protected]\fP"

.PP
Definition at line 40 of file LevelAnimationRenderer\&.java\&.
.SS "\fBLinearFunction\fP game\&.gui\&.level\&.LevelAnimationRenderer\&.getCurrentFunction ()\fC [protected]\fP"

.PP
Definition at line 32 of file LevelAnimationRenderer\&.java\&.
.SS "void game\&.gui\&.level\&.LevelAnimationRenderer\&.setCurrentFunction (\fBLinearFunction\fP currentFunction)"

.PP
Definition at line 28 of file LevelAnimationRenderer\&.java\&.
.SS "abstract void game\&.gui\&.level\&.LevelAnimationRenderer\&.startAnimation (Canvas canvas)\fC [abstract]\fP"

.SS "abstract void game\&.gui\&.level\&.LevelAnimationRenderer\&.stopAnimation ()\fC [abstract]\fP, \fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
