.TH "game.level.Submit" 3 "Sun Jun 3 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.level.Submit
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSubmit\fP (\fBLinearFunction\fP function)"
.br
.ti -1c
.RI "\fBSubmit\fP (\fBPoint\fP p)"
.br
.ti -1c
.RI "\fBSubmitType\fP \fBgetSubmitType\fP ()"
.br
.ti -1c
.RI "Object \fBgetSubmit\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 10 of file Submit\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "game\&.level\&.Submit\&.Submit (\fBLinearFunction\fP function)"

.PP
Definition at line 18 of file Submit\&.java\&.
.SS "game\&.level\&.Submit\&.Submit (\fBPoint\fP p)"

.PP
Definition at line 23 of file Submit\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Object game\&.level\&.Submit\&.getSubmit ()"

.PP
Definition at line 32 of file Submit\&.java\&.
.SS "\fBSubmitType\fP game\&.level\&.Submit\&.getSubmitType ()"

.PP
Definition at line 28 of file Submit\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
