.TH "game.gui.component.StatusMessage" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.gui.component.StatusMessage
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBdisplay\fP (Node node, \fBStatusMessageType\fP messageType)"
.br
.ti -1c
.RI "static void \fBdisplay\fP (Node node, \fBStatusMessageType\fP messageType, String message)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 24 of file StatusMessage\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void game\&.gui\&.component\&.StatusMessage\&.display (Node node, \fBStatusMessageType\fP messageType)\fC [static]\fP"

.PP
Definition at line 26 of file StatusMessage\&.java\&.
.SS "static void game\&.gui\&.component\&.StatusMessage\&.display (Node node, \fBStatusMessageType\fP messageType, String message)\fC [static]\fP"

.PP
Definition at line 30 of file StatusMessage\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
