.TH "game.level.SubmitHandler" 3 "Sun Jun 3 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.level.SubmitHandler
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSubmit\fP \fBcreateSubmit\fP (\fBPoint\fP point)"
.br
.ti -1c
.RI "static \fBSubmit\fP \fBcreateSubmit\fP (\fBLinearFunction\fP linearFunction)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 10 of file SubmitHandler\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBSubmit\fP game\&.level\&.SubmitHandler\&.createSubmit (\fBPoint\fP point)\fC [static]\fP"

.PP
Definition at line 11 of file SubmitHandler\&.java\&.
.SS "static \fBSubmit\fP game\&.level\&.SubmitHandler\&.createSubmit (\fBLinearFunction\fP linearFunction)\fC [static]\fP"

.PP
Definition at line 16 of file SubmitHandler\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
