.TH "game.module.sprite.Sprite" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.module.sprite.Sprite
.SH SYNOPSIS
.br
.PP
.PP
Inherits Transition\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSprite\fP (ImageView imageView, Duration duration, int count, int columns, int offsetX, int offsetY, int width, int height)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinterpolate\fP (double k)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 13 of file Sprite\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "game\&.module\&.sprite\&.Sprite\&.Sprite (ImageView imageView, Duration duration, int count, int columns, int offsetX, int offsetY, int width, int height)"

.PP
Definition at line 25 of file Sprite\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void game\&.module\&.sprite\&.Sprite\&.interpolate (double k)\fC [protected]\fP"

.PP
Definition at line 43 of file Sprite\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
