.TH "game.controller.LevelState" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.controller.LevelState
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLEVEL_1\fP"
.br
.ti -1c
.RI "\fBLEVEL_2\fP"
.br
.ti -1c
.RI "\fBLEVEL_3\fP"
.br
.ti -1c
.RI "\fBLEVEL_4\fP"
.br
.ti -1c
.RI "\fBLEVEL_END\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Constants for the levels\&. LEVEL_END is used, when the last level is reached\&. 
.PP
\fBAuthor:\fP
.RS 4
Marco 
.RE
.PP

.PP
Definition at line 8 of file LevelState\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "game\&.controller\&.LevelState\&.LEVEL_1"

.PP
Definition at line 9 of file LevelState\&.java\&.
.SS "game\&.controller\&.LevelState\&.LEVEL_2"

.PP
Definition at line 10 of file LevelState\&.java\&.
.SS "game\&.controller\&.LevelState\&.LEVEL_3"

.PP
Definition at line 11 of file LevelState\&.java\&.
.SS "game\&.controller\&.LevelState\&.LEVEL_4"

.PP
Definition at line 12 of file LevelState\&.java\&.
.SS "game\&.controller\&.LevelState\&.LEVEL_END"

.PP
Definition at line 13 of file LevelState\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
