.TH "C:/Bitbucket/uboote/uboote/client/LaserPiratesClient/src/game/level/Level.java" 3 "Sun Jun 24 2018" "LaserPirates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Bitbucket/uboote/uboote/client/LaserPiratesClient/src/game/level/Level.java
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBgame\&.level\&.Level\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBgame\&.level\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LaserPirates from the source code\&.
